name: Generate Snake (Test)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Настраиваем Git пользователя для фиктивных коммитов
      - name: Set Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Создаём фиктивные коммиты
      - name: Create dummy commits
        run: |
          mkdir -p dummy
          for i in {1..10}; do
            echo "dummy $i" >> dummy/file.txt
            git add dummy/file.txt
            git commit -m "Dummy commit $i"
          done

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: reinhardUpper
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: List dist
        run: ls -la dist

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          create_branch: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
